<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:ocl.ecore="http://www.eclipse.org/ocl/1.1.0/Ecore">
  <ecore:EPackage name="oclstdlib" nsURI="http://www.eclipse.org/ocldi/stdlib/1.1"
      nsPrefix="oclstdlib">
    <eClassifiers xsi:type="ocl.ecore:AnyType" name="OclAny"/>
    <eClassifiers xsi:type="ecore:EClass" name="OclAny_Class">
      <eAnnotations source="http://www.eclipse.org/ocl/1.1.0/OCL" references="#/0/OclAny"/>
    </eClassifiers>
    <eClassifiers xsi:type="ocl.ecore:VoidType"/>
    <eClassifiers xsi:type="ecore:EClass" name="OclVoid_Class">
      <eAnnotations source="http://www.eclipse.org/ocl/1.1.0/OCL" references="#/0/OclVoid"/>
    </eClassifiers>
    <eClassifiers xsi:type="ocl.ecore:InvalidType"/>
    <eClassifiers xsi:type="ecore:EClass" name="Invalid_Class">
      <eAnnotations source="http://www.eclipse.org/ocl/1.1.0/OCL" references="#/0/Invalid"/>
    </eClassifiers>
    <eClassifiers xsi:type="ocl.ecore:PrimitiveType" name="Boolean" instanceClassName="java.lang.Boolean"/>
    <eClassifiers xsi:type="ecore:EClass" name="Boolean_Class">
      <eAnnotations source="http://www.eclipse.org/ocl/1.1.0/OCL" references="#/0/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ocl.ecore:PrimitiveType" name="Integer" instanceClassName="java.lang.Integer"/>
    <eClassifiers xsi:type="ecore:EClass" name="Integer_Class">
      <eAnnotations source="http://www.eclipse.org/ocl/1.1.0/OCL" references="#/0/Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ocl.ecore:PrimitiveType" name="UnlimitedNatural"/>
    <eClassifiers xsi:type="ecore:EClass" name="UnlimitedNatural_Class">
      <eAnnotations source="http://www.eclipse.org/ocl/1.1.0/OCL" references="#/0/UnlimitedNatural"/>
    </eClassifiers>
    <eClassifiers xsi:type="ocl.ecore:PrimitiveType" name="Real" instanceClassName="java.lang.Double"/>
    <eClassifiers xsi:type="ecore:EClass" name="Real_Class">
      <eAnnotations source="http://www.eclipse.org/ocl/1.1.0/OCL" references="#/0/Real"/>
    </eClassifiers>
    <eClassifiers xsi:type="ocl.ecore:PrimitiveType" name="String" instanceClassName="java.lang.String"/>
    <eClassifiers xsi:type="ecore:EClass" name="String_Class">
      <eAnnotations source="http://www.eclipse.org/ocl/1.1.0/OCL" references="#/0/String"/>
      <eOperations name="trim" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="regexMatch" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eParameters name="substring" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="charAt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eParameters name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eOperations>
      <eOperations name="startsWith" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="radix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="endsWith" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="suffix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ocl.ecore:TypeType" name="OclType"/>
    <eClassifiers xsi:type="ecore:EClass" name="OclType_Class">
      <eAnnotations source="http://www.eclipse.org/ocl/1.1.0/OCL" references="#/0/OclType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ocl.ecore:MessageType"/>
    <eClassifiers xsi:type="ocl.ecore:ElementType" name="OclElement"/>
    <eClassifiers xsi:type="ocl.ecore:ElementType" name="State"/>
    <eClassifiers xsi:type="ocl.ecore:ElementType" name="OclExpression"/>
    <eClassifiers xsi:type="ocl.ecore:CollectionType" name="Collection(T)" elementType="#/0/T"/>
    <eClassifiers xsi:type="ecore:EClass" name="Collection(T)_Class">
      <eAnnotations source="http://www.eclipse.org/ocl/1.1.0/OCL" references="#/0/Collection(T)"/>
    </eClassifiers>
    <eClassifiers xsi:type="ocl.ecore:SetType" name="Set(T)" instanceClassName="java.util.Set"
        elementType="#/0/T"/>
    <eClassifiers xsi:type="ecore:EClass" name="Set(T)_Class">
      <eAnnotations source="http://www.eclipse.org/ocl/1.1.0/OCL" references="#/0/Set(T)"/>
    </eClassifiers>
    <eClassifiers xsi:type="ocl.ecore:OrderedSetType" name="OrderedSet(T)" instanceClassName="java.util.LinkedHashSet"
        elementType="#/0/T"/>
    <eClassifiers xsi:type="ecore:EClass" name="OrderedSet(T)_Class">
      <eAnnotations source="http://www.eclipse.org/ocl/1.1.0/OCL" references="#/0/OrderedSet(T)"/>
    </eClassifiers>
    <eClassifiers xsi:type="ocl.ecore:BagType" name="Bag(T)" instanceClassName="org.eclipse.ocl.util.Bag"
        elementType="#/0/T"/>
    <eClassifiers xsi:type="ecore:EClass" name="Bag(T)_Class">
      <eAnnotations source="http://www.eclipse.org/ocl/1.1.0/OCL" references="#/0/Bag(T)"/>
    </eClassifiers>
    <eClassifiers xsi:type="ocl.ecore:SequenceType" name="Sequence(T)" instanceClassName="java.util.List"
        elementType="#/0/T"/>
    <eClassifiers xsi:type="ecore:EClass" name="Sequence(T)_Class">
      <eAnnotations source="http://www.eclipse.org/ocl/1.1.0/OCL" references="#/0/Sequence(T)"/>
    </eClassifiers>
    <eClassifiers xsi:type="ocl.ecore:AnyType" name="T"/>
    <eClassifiers xsi:type="ecore:EClass" name="T_Class">
      <eAnnotations source="http://www.eclipse.org/ocl/1.1.0/OCL" references="#/0/T"/>
    </eClassifiers>
    <eClassifiers xsi:type="ocl.ecore:AnyType" name="T2"/>
    <eClassifiers xsi:type="ecore:EClass" name="T2_Class">
      <eAnnotations source="http://www.eclipse.org/ocl/1.1.0/OCL" references="#/0/T2"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="tuples">
    <eClassifiers xsi:type="ocl.ecore:TupleType" name="Tuple(first : T, second : T2)"
        instanceClassName="org.eclipse.ocl.util.Tuple">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="first" eType="#/0/T"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="second" eType="#/0/T2"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="collections">
    <eClassifiers xsi:type="ocl.ecore:SetType" name="Set(Tuple(first : T, second : T2))"
        instanceClassName="java.util.Set" elementType="#/1/Tuple(first%20%3A%20T%2C%20second%20%3A%20T2)"/>
    <eClassifiers xsi:type="ocl.ecore:CollectionType" name="Collection(T2)" elementType="#/0/T2"/>
    <eClassifiers xsi:type="ocl.ecore:SetType" name="Set(T2)" instanceClassName="java.util.Set"
        elementType="#/0/T2"/>
    <eClassifiers xsi:type="ocl.ecore:BagType" name="Bag(T2)" instanceClassName="org.eclipse.ocl.util.Bag"
        elementType="#/0/T2"/>
    <eClassifiers xsi:type="ocl.ecore:SequenceType" name="Sequence(T2)" instanceClassName="java.util.List"
        elementType="#/0/T2"/>
  </ecore:EPackage>
</xmi:XMI>
