<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model"
    nsURI="http://www.topcased.org/Diagrams/1.0" nsPrefix="diagrams">
  <eClassifiers xsi:type="ecore:EClass" name="Diagrams">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagrams" ordered="false"
        upperBound="-1" eType="ecore:EClass ../../org.topcased.modeler.di/model/DI.ecore#//Diagram"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activeDiagram" eType="ecore:EClass ../../org.topcased.modeler.di/model/DI.ecore#//Diagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subdiagrams" ordered="false"
        upperBound="-1" eType="#//Diagrams" containment="true" eOpposite="#//Diagrams/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Diagrams"
        eOpposite="#//Diagrams/subdiagrams"/>
  </eClassifiers>
</ecore:EPackage>
